# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.9.5

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: lein test

  deploy:
    docker:
      - image: circleci/clojure:lein-2.9.5

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"

    steps:
      - when:
          condition:
            matches:
              pattern: "^master$"
              value: << pipeline.git.branch >>
          steps:
            - checkout
            - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "project.clj" }}
                  - v1-dependencies-
            - save_cache:
                paths:
                  - ~/.m2
                key: v1-dependencies-{{ checksum "project.clj" }}
            - run: lein do clean, deploy clojars


workflows:
  build:
    jobs:
      - test
      - deploy
